---
  version: 2

  updates:
    - directory: /
      package-ecosystem: npm
      schedule:
        interval: daily
      versioning-strategy: increase
      ignore:
        - dependency-name: '@types/node'
          versions: ['>= 11.a']

    - directory: /
      package-ecosystem: github-actions
      schedule:
        interval: daily
