name: Version Bump

on:
  repository_dispatch:
  schedule:
    - cron: '0 12 * * MON-FRI'

jobs:
  submit_version_bump:
    name: Submit Version Bump
    runs-on: ubuntu-latest

    if: github.ref == 'master' || github.event_name == 'repository_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |-
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Update Version
        id: update_version
        run: |-
          npx standard-version
          echo "::set-output name=version::$(node -p 'require("./package.json").version;')"

      - name: Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'release: v${{ steps.update_version.outputs.version }}'
          body: 'See CHANGELOG.md'
          branch: release/automated

