name: Validation Build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}

      - name: Set up Node
        uses: actions/setup-node@master
        with:
          node-version: ${{matrix.node-version}}

      - name: Locate Yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore Yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |-
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
